[2021-02-19T21:50:27.991681+01:00] php.DEBUG: Warning: include(/home/hurx6457/public_html/logtime/var/cache/de_/App_KernelDevDebugContainer.php): failed to open stream: No such file or directory {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/Kernel.php","line":469,"trace":[{"file":"/home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/Kernel.php","line":469,"function":"include"}],"count":1}}} []
[2021-02-19T21:50:27.992668+01:00] php.DEBUG: Warning: include(): Failed opening '/home/hurx6457/public_html/logtime/var/cache/de_/App_KernelDevDebugContainer.php' for inclusion (include_path='.:/opt/alt/php74/usr/share/pear') [] []
[2021-02-19T21:53:03.271869+01:00] php.INFO: Deprecated: Function ReflectionType::__toString() is deprecated {"exception":"[object] (ErrorException(code: 0): Deprecated: Function ReflectionType::__toString() is deprecated at /home/hurx6457/public_html/logtime/vendor/symfony/maker-bundle/src/Maker/MakeAuthenticator.php:406)"} []
[2021-02-19T22:00:10.293163+01:00] php.DEBUG: Warning: include(/home/hurx6457/public_html/logtime/var/cache/de_/App_KernelDevDebugContainer.php): failed to open stream: No such file or directory {"exception":{"Symfony\\Component\\ErrorHandler\\Exception\\SilencedErrorContext":{"severity":2,"file":"/home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/Kernel.php","line":469,"trace":[{"file":"/home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/Kernel.php","line":469,"function":"include"}],"count":1}}} []
[2021-02-19T22:00:10.294134+01:00] php.DEBUG: Warning: include(): Failed opening '/home/hurx6457/public_html/logtime/var/cache/de_/App_KernelDevDebugContainer.php' for inclusion (include_path='.:/opt/alt/php74/usr/share/pear') [] []
[2021-02-19T22:03:18.247078+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-19T22:03:18.530619+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"d518af"},"request_uri":"https://logtime.lineac2.fr/_wdt/d518af","method":"GET"} []
[2021-02-19T22:03:18.611266+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://logtime.lineac2.fr/")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://logtime.lineac2.fr/\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-19T22:04:10.309889+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-02-19T22:04:10.312351+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-02-19T22:04:10.325372+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'hurx6457_logtime' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-02-19T22:04:10.327579+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'hurx6457_logtime' /*!50116 AND c.constraint_schema = 'hurx6457_logtime' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-02-19T22:04:10.328443+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'hurx6457_logtime' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-02-19T22:04:10.329067+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-02-19T22:04:10.330087+01:00] doctrine.DEBUG: SELECT * FROM doctrine_migration_versions [] []
[2021-02-19T22:04:10.332655+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-02-19T22:04:10.333263+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-02-19T22:04:10.333847+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'hurx6457_logtime' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-02-19T22:04:10.334801+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'hurx6457_logtime' /*!50116 AND c.constraint_schema = 'hurx6457_logtime' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-02-19T22:04:10.335468+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'hurx6457_logtime' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-02-19T22:04:10.335993+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-02-19T22:04:10.336565+01:00] doctrine.DEBUG: SELECT * FROM doctrine_migration_versions [] []
[2021-02-19T22:04:20.983056+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-02-19T22:04:20.983800+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'hurx6457_logtime' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-02-19T22:04:20.985001+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'hurx6457_logtime' /*!50116 AND c.constraint_schema = 'hurx6457_logtime' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-02-19T22:04:20.985863+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'hurx6457_logtime' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-02-19T22:04:20.986490+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-02-19T22:04:20.987094+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'hurx6457_logtime' AND TABLE_NAME = 'user' ORDER BY ORDINAL_POSITION ASC [] []
[2021-02-19T22:04:20.988217+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'user' */ WHERE k.table_name = 'user' AND k.table_schema = 'hurx6457_logtime' /*!50116 AND c.constraint_schema = 'hurx6457_logtime' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-02-19T22:04:20.988943+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'user' AND TABLE_SCHEMA = 'hurx6457_logtime' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-02-19T22:04:20.989565+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'user' [] []
[2021-02-19T22:04:43.516253+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-02-19T22:04:43.532854+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'hurx6457_logtime' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-02-19T22:04:43.535114+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'hurx6457_logtime' /*!50116 AND c.constraint_schema = 'hurx6457_logtime' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-02-19T22:04:43.535920+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'hurx6457_logtime' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-02-19T22:04:43.536490+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-02-19T22:04:43.541166+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-02-19T22:04:43.541674+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-02-19T22:04:43.542139+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'hurx6457_logtime' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-02-19T22:04:43.543104+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'hurx6457_logtime' /*!50116 AND c.constraint_schema = 'hurx6457_logtime' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-02-19T22:04:43.543734+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'hurx6457_logtime' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-02-19T22:04:43.544238+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-02-19T22:04:43.544768+01:00] doctrine.DEBUG: SELECT * FROM doctrine_migration_versions [] []
[2021-02-19T22:04:43.545604+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-02-19T22:04:43.546451+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-02-19T22:04:43.546867+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'hurx6457_logtime' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-02-19T22:04:43.547718+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'hurx6457_logtime' /*!50116 AND c.constraint_schema = 'hurx6457_logtime' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-02-19T22:04:43.548303+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'hurx6457_logtime' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-02-19T22:04:43.548792+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-02-19T22:04:43.549330+01:00] doctrine.DEBUG: SELECT * FROM doctrine_migration_versions [] []
[2021-02-19T22:04:49.278585+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-02-19T22:04:49.279283+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-02-19T22:04:49.279753+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'hurx6457_logtime' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-02-19T22:04:49.280771+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'hurx6457_logtime' /*!50116 AND c.constraint_schema = 'hurx6457_logtime' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-02-19T22:04:49.281410+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'hurx6457_logtime' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-02-19T22:04:49.281904+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-02-19T22:04:49.282468+01:00] doctrine.DEBUG: SELECT * FROM doctrine_migration_versions [] []
[2021-02-19T22:04:49.292403+01:00] doctrine.DEBUG: "START TRANSACTION" [] []
[2021-02-19T22:04:49.312745+01:00] doctrine.DEBUG: DROP INDEX UNIQ_8D93D649F85E0677 ON user [] []
[2021-02-19T22:04:49.320507+01:00] doctrine.DEBUG: ALTER TABLE user DROP username, CHANGE email email VARCHAR(180) NOT NULL [] []
[2021-02-19T22:04:49.359866+01:00] doctrine.DEBUG: CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON user (email) [] []
[2021-02-19T22:04:49.368532+01:00] doctrine.DEBUG: SHOW FULL TABLES WHERE Table_type = 'BASE TABLE' [] []
[2021-02-19T22:04:49.369185+01:00] doctrine.DEBUG: SELECT COLUMN_NAME AS Field, COLUMN_TYPE AS Type, IS_NULLABLE AS `Null`, COLUMN_KEY AS `Key`, COLUMN_DEFAULT AS `Default`, EXTRA AS Extra, COLUMN_COMMENT AS Comment, CHARACTER_SET_NAME AS CharacterSet, COLLATION_NAME AS Collation FROM information_schema.COLUMNS WHERE TABLE_SCHEMA = 'hurx6457_logtime' AND TABLE_NAME = 'doctrine_migration_versions' ORDER BY ORDINAL_POSITION ASC [] []
[2021-02-19T22:04:49.370174+01:00] doctrine.DEBUG: SELECT DISTINCT k.`CONSTRAINT_NAME`, k.`COLUMN_NAME`, k.`REFERENCED_TABLE_NAME`, k.`REFERENCED_COLUMN_NAME` /*!50116 , c.update_rule, c.delete_rule */ FROM information_schema.key_column_usage k /*!50116 INNER JOIN information_schema.referential_constraints c ON   c.constraint_name = k.constraint_name AND   c.table_name = 'doctrine_migration_versions' */ WHERE k.table_name = 'doctrine_migration_versions' AND k.table_schema = 'hurx6457_logtime' /*!50116 AND c.constraint_schema = 'hurx6457_logtime' */ AND k.`REFERENCED_COLUMN_NAME` is not NULL [] []
[2021-02-19T22:04:49.370841+01:00] doctrine.DEBUG: SELECT NON_UNIQUE AS Non_Unique, INDEX_NAME AS Key_name, COLUMN_NAME AS Column_Name, SUB_PART AS Sub_Part, INDEX_TYPE AS Index_Type FROM information_schema.STATISTICS WHERE TABLE_NAME = 'doctrine_migration_versions' AND TABLE_SCHEMA = 'hurx6457_logtime' ORDER BY SEQ_IN_INDEX ASC [] []
[2021-02-19T22:04:49.371363+01:00] doctrine.DEBUG: SELECT ENGINE, AUTO_INCREMENT, TABLE_COLLATION, TABLE_COMMENT, CREATE_OPTIONS FROM information_schema.TABLES WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'doctrine_migration_versions' [] []
[2021-02-19T22:04:49.372018+01:00] doctrine.DEBUG: INSERT INTO doctrine_migration_versions (version, executed_at, execution_time) VALUES (?, ?, ?) ["DoctrineMigrations\\Version [...]","2021-02-19T22:04:49+01:00",76] []
[2021-02-19T22:04:49.373375+01:00] doctrine.DEBUG: "COMMIT" [] []
[2021-02-19T22:05:00.483954+01:00] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"https://logtime.lineac2.fr/register","method":"GET"} []
[2021-02-19T22:05:00.491933+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-19T22:05:00.492038+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-19T22:05:00.492106+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-19T22:05:00.680778+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-02-19T22:05:00.874748+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"2dc3bf"},"request_uri":"https://logtime.lineac2.fr/_wdt/2dc3bf","method":"GET"} []
[2021-02-19T22:05:00.990585+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://logtime.lineac2.fr/register")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://logtime.lineac2.fr/register\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-19T22:05:17.762832+01:00] request.INFO: Matched route "app_register". {"route":"app_register","route_parameters":{"_route":"app_register","_controller":"App\\Controller\\RegistrationController::register"},"request_uri":"https://logtime.lineac2.fr/register","method":"POST"} []
[2021-02-19T22:05:17.767768+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-19T22:05:17.767890+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-19T22:05:17.767959+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-19T22:05:17.768392+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-02-19T22:05:17.857131+01:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.is_verified AS is_verified_5 FROM user t0 WHERE t0.email = ? ["snadaud@free.fr"] []
[2021-02-19T22:05:18.288338+01:00] doctrine.DEBUG: "START TRANSACTION" [] []
[2021-02-19T22:05:18.291338+01:00] doctrine.DEBUG: INSERT INTO user (email, roles, password, is_verified) VALUES (?, ?, ?, ?) {"1":"snadaud@free.fr","2":[],"3":"$argon2id$v=19$m=65536,t=4 [...]","4":false} []
[2021-02-19T22:05:18.292044+01:00] doctrine.DEBUG: "COMMIT" [] []
[2021-02-19T22:05:18.315403+01:00] app.DEBUG: Email transport "Symfony\Component\Mailer\Transport\Smtp\SmtpTransport" starting [] []
[2021-02-19T22:05:18.504442+01:00] app.DEBUG: Email transport "Symfony\Component\Mailer\Transport\Smtp\SmtpTransport" started [] []
[2021-02-19T22:05:18.613176+01:00] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2021-02-19T22:05:18.640560+01:00] app.DEBUG: Email transport "Symfony\Component\Mailer\Transport\Smtp\SmtpTransport" stopping [] []
[2021-02-19T22:05:18.645464+01:00] app.DEBUG: Email transport "Symfony\Component\Mailer\Transport\Smtp\SmtpTransport" stopped [] []
[2021-02-19T22:05:18.738711+01:00] request.INFO: Matched route "user". {"route":"user","route_parameters":{"_route":"user","_controller":"App\\Controller\\UserController::index"},"request_uri":"https://logtime.lineac2.fr/user","method":"GET"} []
[2021-02-19T22:05:18.742204+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-19T22:05:18.742321+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-19T22:05:18.742383+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-19T22:05:18.752487+01:00] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
[2021-02-19T22:05:18.763251+01:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.is_verified AS is_verified_5 FROM user t0 WHERE t0.id = ? [1] []
[2021-02-19T22:05:18.764494+01:00] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"snadaud@free.fr"} []
[2021-02-19T22:05:19.076544+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"3c2e7b"},"request_uri":"https://logtime.lineac2.fr/_wdt/3c2e7b","method":"GET"} []
[2021-02-19T22:05:19.140300+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://logtime.lineac2.fr/user")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://logtime.lineac2.fr/user\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-19T22:05:34.095540+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://logtime.lineac2.fr/register")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://logtime.lineac2.fr/register\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-19T22:05:37.312409+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://logtime.lineac2.fr/")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://logtime.lineac2.fr/\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-19T22:05:45.401729+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-19T22:05:45.644219+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"6216c8"},"request_uri":"https://logtime.lineac2.fr/_wdt/6216c8","method":"GET"} []
[2021-02-19T22:05:45.738026+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://logtime.lineac2.fr/")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://logtime.lineac2.fr/\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-19T22:06:22.831270+01:00] request.INFO: Matched route "app_verify_email". {"route":"app_verify_email","route_parameters":{"_route":"app_verify_email","_controller":"App\\Controller\\RegistrationController::verifyUserEmail"},"request_uri":"https://logtime.lineac2.fr/verify/email?expires=1613772318&signature=%2FSRPxAtbhfSLVyF%2BEOnYSj38DNmsX2t6J1XMRih16c8%3D&token=cOj9jb6yhetrH9F%2BIn0a33oFAxrZpA7pbSXwXubxEoQ%3D","method":"GET"} []
[2021-02-19T22:06:22.835864+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-19T22:06:22.835976+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-19T22:06:22.836045+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-19T22:06:22.841480+01:00] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
[2021-02-19T22:06:22.856331+01:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.is_verified AS is_verified_5 FROM user t0 WHERE t0.id = ? [1] []
[2021-02-19T22:06:22.857744+01:00] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"snadaud@free.fr"} []
[2021-02-19T22:06:22.860138+01:00] doctrine.DEBUG: "START TRANSACTION" [] []
[2021-02-19T22:06:22.860549+01:00] doctrine.DEBUG: UPDATE user SET is_verified = ? WHERE id = ? [true,1] []
[2021-02-19T22:06:22.861336+01:00] doctrine.DEBUG: "COMMIT" [] []
[2021-02-19T22:06:22.866421+01:00] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2021-02-19T22:06:22.957744+01:00] request.INFO: Matched route "user". {"route":"user","route_parameters":{"_route":"user","_controller":"App\\Controller\\UserController::index"},"request_uri":"https://logtime.lineac2.fr/user","method":"GET"} []
[2021-02-19T22:06:22.960658+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-19T22:06:22.960751+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-19T22:06:22.960822+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-19T22:06:22.968018+01:00] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
[2021-02-19T22:06:22.977922+01:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.is_verified AS is_verified_5 FROM user t0 WHERE t0.id = ? [1] []
[2021-02-19T22:06:22.979455+01:00] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"snadaud@free.fr"} []
[2021-02-19T22:06:23.341763+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"f2c2b8"},"request_uri":"https://logtime.lineac2.fr/_wdt/f2c2b8","method":"GET"} []
[2021-02-19T22:06:23.442628+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://logtime.lineac2.fr/user")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://logtime.lineac2.fr/user\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-19T22:06:30.901139+01:00] request.INFO: Matched route "_profiler_open_file". {"route":"_profiler_open_file","route_parameters":{"_route":"_profiler_open_file","_controller":"web_profiler.controller.profiler::openAction"},"request_uri":"https://logtime.lineac2.fr/_profiler/open?file=src%2FController%2FUserController.php&line=0","method":"GET"} []
[2021-02-19T22:06:43.182027+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://logtime.lineac2.fr/user")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://logtime.lineac2.fr/user\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-19T22:06:48.308991+01:00] request.INFO: Matched route "_profiler_open_file". {"route":"_profiler_open_file","route_parameters":{"_route":"_profiler_open_file","_controller":"web_profiler.controller.profiler::openAction"},"request_uri":"https://logtime.lineac2.fr/_profiler/open?file=templates%2Fuser%2Findex.html.twig&line=0","method":"GET"} []
[2021-02-20T02:00:58.220449+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "https://logtime.lineac2.fr/index.php")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"https://logtime.lineac2.fr/index.php\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-20T05:13:20.433720+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "https://www.logtime.lineac2.fr/index.php")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"https://www.logtime.lineac2.fr/index.php\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-20T05:13:20.569724+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-20T05:13:20.813074+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "https://logtime.lineac2.fr/index.php")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"https://logtime.lineac2.fr/index.php\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-20T05:13:20.927668+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-20T09:45:15.210007+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-20T09:52:36.868772+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-20T11:41:32.258714+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "https://lineac2.fr/test/")" at /home/hurx6457/public_html/test/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"https://lineac2.fr/test/\") at /home/hurx6457/public_html/test/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/test/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-20T11:41:32.615209+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"742a62"},"request_uri":"https://lineac2.fr/test/public/_wdt/742a62","method":"GET"} []
[2021-02-20T19:22:44.628582+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "https://lineac2.fr/logtime/")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"https://lineac2.fr/logtime/\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-20T19:22:44.994372+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"c42509"},"request_uri":"https://lineac2.fr/logtime/public/_wdt/c42509","method":"GET"} []
[2021-02-20T19:22:51.823105+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://lineac2.fr/logtime/public/login","method":"GET"} []
[2021-02-20T19:22:51.831195+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-20T19:22:51.831264+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-20T19:22:51.831307+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-20T19:22:51.904856+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-02-20T19:22:52.133468+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"450536"},"request_uri":"https://lineac2.fr/logtime/public/_wdt/450536","method":"GET"} []
[2021-02-20T19:22:54.409584+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://lineac2.fr/logtime/public/login","method":"POST"} []
[2021-02-20T19:22:54.412340+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-20T19:22:54.412394+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-20T19:22:54.412439+01:00] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-20T19:22:54.413506+01:00] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-20T19:22:54.463907+01:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.is_verified AS is_verified_5 FROM user t0 WHERE t0.email = ? LIMIT 1 ["snadaud@free.fr"] []
[2021-02-20T19:22:54.828069+01:00] security.INFO: Guard authentication successful! {"token":{"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken":"PostAuthenticationGuardToken(user=\"snadaud@free.fr\", authenticated=true, roles=\"ROLE_USER\")"},"authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-20T19:22:54.831493+01:00] security.DEBUG: Guard authenticator set success response. {"response":{"Symfony\\Component\\HttpFoundation\\RedirectResponse":"HTTP/1.0 302 Found\r\nCache-Control: no-cache, private\r\nDate:          Sat, 20 Feb 2021 18:22:54 GMT\r\nLocation:      /logtime/public/user\r\n\r\n<!DOCTYPE html>\n<html>\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta http-equiv=\"refresh\" content=\"0;url='/logtime/public/user'\" />\n\n        <title>Redirecting to /logtime/public/user</title>\n    </head>\n    <body>\n        Redirecting to <a href=\"/logtime/public/user\">/logtime/public/user</a>.\n    </body>\n</html>"},"authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-20T19:22:54.831631+01:00] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-20T19:22:54.831689+01:00] security.DEBUG: The "App\Security\LoginFormAuthenticator" authenticator set the response. Any later authenticator will not be called {"authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-20T19:22:54.835436+01:00] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2021-02-20T19:22:54.921466+01:00] request.INFO: Matched route "user". {"route":"user","route_parameters":{"_route":"user","_controller":"App\\Controller\\UserController::index"},"request_uri":"https://lineac2.fr/logtime/public/user","method":"GET"} []
[2021-02-20T19:22:54.925367+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-20T19:22:54.925477+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-20T19:22:54.925537+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-20T19:22:54.979435+01:00] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
[2021-02-20T19:22:54.991298+01:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.is_verified AS is_verified_5 FROM user t0 WHERE t0.id = ? [1] []
[2021-02-20T19:22:54.992315+01:00] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"snadaud@free.fr"} []
[2021-02-20T19:22:55.195272+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"34214d"},"request_uri":"https://lineac2.fr/logtime/public/_wdt/34214d","method":"GET"} []
[2021-02-20T21:13:30.185430+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "https://logtime.lineac2.fr/index.php")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"https://logtime.lineac2.fr/index.php\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-20T21:13:30.512010+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-20T21:13:33.345282+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "https://www.logtime.lineac2.fr/index.php")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"https://www.logtime.lineac2.fr/index.php\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-20T21:13:33.467123+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-21T21:13:26.016112+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "https://www.logtime.lineac2.fr/index.php")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"https://www.logtime.lineac2.fr/index.php\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-21T21:13:26.258297+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-21T21:13:26.274655+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "https://logtime.lineac2.fr/index.php")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"https://logtime.lineac2.fr/index.php\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-21T21:13:26.388467+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-22T03:51:18.852849+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-22T04:46:39.532657+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-22T05:35:35.845421+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-22T06:36:04.541945+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-22T18:14:54.520426+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /" (from "https://lineac2.fr/logtime/")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" (from \"https://lineac2.fr/logtime/\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-22T18:14:54.820731+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"ba7c53"},"request_uri":"https://lineac2.fr/logtime/public/_wdt/ba7c53","method":"GET"} []
[2021-02-22T18:15:05.914133+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://lineac2.fr/logtime/public/login","method":"GET"} []
[2021-02-22T18:15:06.016226+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-22T18:15:06.016378+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-22T18:15:06.016461+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-22T18:15:06.191776+01:00] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
[2021-02-22T18:15:06.335797+01:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("An exception occurred in driver: SQLSTATE[28000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)")." at /home/hurx6457/public_html/logtime/templates/security/login.html.twig line 11 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"An exception occurred in driver: SQLSTATE[28000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES)\"). at /home/hurx6457/public_html/logtime/templates/security/login.html.twig:11)\n[previous exception] [object] (Doctrine\\DBAL\\Exception\\ConnectionException(code: 0): An exception occurred in driver: SQLSTATE[28000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at /home/hurx6457/public_html/logtime/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php:112)\n[previous exception] [object] (Doctrine\\DBAL\\Driver\\PDO\\Exception(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at /home/hurx6457/public_html/logtime/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18)\n[previous exception] [object] (PDOException(code: 1045): SQLSTATE[28000] [1045] Access denied for user 'db_user'@'localhost' (using password: YES) at /home/hurx6457/public_html/logtime/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:38)"} []
[2021-02-22T18:15:07.561296+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"86ca73"},"request_uri":"https://lineac2.fr/logtime/public/_wdt/86ca73","method":"GET"} []
[2021-02-22T18:18:08.912928+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://lineac2.fr/logtime/public/login","method":"GET"} []
[2021-02-22T18:18:08.915827+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-22T18:18:08.915895+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-22T18:18:08.915942+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-22T18:18:08.965709+01:00] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
[2021-02-22T18:18:09.313708+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"f34212"},"request_uri":"https://lineac2.fr/logtime/public/_wdt/f34212","method":"GET"} []
[2021-02-24T19:02:17.763054+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-24T19:02:18.107042+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"2ce62b"},"request_uri":"https://logtime.lineac2.fr/_wdt/2ce62b","method":"GET"} []
[2021-02-24T19:02:18.225560+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://logtime.lineac2.fr/")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://logtime.lineac2.fr/\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-24T19:02:24.544908+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://logtime.lineac2.fr/login","method":"GET"} []
[2021-02-24T19:02:24.550587+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-24T19:02:24.550697+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-24T19:02:24.550771+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-24T19:02:24.587509+01:00] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
[2021-02-24T19:02:24.817961+01:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.is_verified AS is_verified_5 FROM user t0 WHERE t0.id = ? [1] []
[2021-02-24T19:02:24.849071+01:00] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"snadaud@free.fr"} []
[2021-02-24T19:02:24.853351+01:00] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2021-02-24T19:02:25.125520+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"a1248b"},"request_uri":"https://logtime.lineac2.fr/_wdt/a1248b","method":"GET"} []
[2021-02-24T19:02:25.624820+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://logtime.lineac2.fr/login")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://logtime.lineac2.fr/login\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-24T19:02:27.832261+01:00] request.INFO: Matched route "app_login". {"route":"app_login","route_parameters":{"_route":"app_login","_controller":"App\\Controller\\SecurityController::login"},"request_uri":"https://logtime.lineac2.fr/login","method":"POST"} []
[2021-02-24T19:02:27.837826+01:00] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
[2021-02-24T19:02:27.854009+01:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.is_verified AS is_verified_5 FROM user t0 WHERE t0.id = ? [1] []
[2021-02-24T19:02:27.855140+01:00] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"snadaud@free.fr"} []
[2021-02-24T19:02:27.855263+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-24T19:02:27.855332+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-24T19:02:27.855417+01:00] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-24T19:02:27.857317+01:00] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-24T19:02:27.858385+01:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.is_verified AS is_verified_5 FROM user t0 WHERE t0.email = ? LIMIT 1 ["snadaud@free.fr"] []
[2021-02-24T19:02:28.288064+01:00] security.INFO: Guard authentication successful! {"token":{"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken":"PostAuthenticationGuardToken(user=\"snadaud@free.fr\", authenticated=true, roles=\"ROLE_USER\")"},"authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-24T19:02:28.317218+01:00] security.DEBUG: Guard authenticator set success response. {"response":{"Symfony\\Component\\HttpFoundation\\RedirectResponse":"HTTP/1.0 302 Found\r\nCache-Control: no-cache, private\r\nDate:          Wed, 24 Feb 2021 18:02:28 GMT\r\nLocation:      /user\r\n\r\n<!DOCTYPE html>\n<html>\n    <head>\n        <meta charset=\"UTF-8\" />\n        <meta http-equiv=\"refresh\" content=\"0;url='/user'\" />\n\n        <title>Redirecting to /user</title>\n    </head>\n    <body>\n        Redirecting to <a href=\"/user\">/user</a>.\n    </body>\n</html>"},"authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-24T19:02:28.317370+01:00] security.DEBUG: Remember me skipped: it is not configured for the firewall. {"authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-24T19:02:28.317450+01:00] security.DEBUG: The "App\Security\LoginFormAuthenticator" authenticator set the response. Any later authenticator will not be called {"authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-24T19:02:28.321374+01:00] security.DEBUG: Stored the security token in the session. {"key":"_security_main"} []
[2021-02-24T19:02:28.424910+01:00] request.INFO: Matched route "user". {"route":"user","route_parameters":{"_route":"user","_controller":"App\\Controller\\UserController::index"},"request_uri":"https://logtime.lineac2.fr/user","method":"GET"} []
[2021-02-24T19:02:28.428208+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-24T19:02:28.428305+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-24T19:02:28.428367+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-24T19:02:28.465187+01:00] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
[2021-02-24T19:02:28.479408+01:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.is_verified AS is_verified_5 FROM user t0 WHERE t0.id = ? [1] []
[2021-02-24T19:02:28.480659+01:00] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"snadaud@free.fr"} []
[2021-02-24T19:02:28.703176+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"eee474"},"request_uri":"https://logtime.lineac2.fr/_wdt/eee474","method":"GET"} []
[2021-02-24T19:02:28.779138+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://logtime.lineac2.fr/user")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://logtime.lineac2.fr/user\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-24T19:12:59.585272+01:00] request.INFO: Matched route "user". {"route":"user","route_parameters":{"_route":"user","_controller":"App\\Controller\\UserController::index"},"request_uri":"https://logtime.lineac2.fr/user","method":"GET"} []
[2021-02-24T19:12:59.590237+01:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
[2021-02-24T19:12:59.590342+01:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-24T19:12:59.590411+01:00] security.DEBUG: Guard authenticator does not support the request. {"firewall_key":"main","authenticator":"App\\Security\\LoginFormAuthenticator"} []
[2021-02-24T19:12:59.599879+01:00] security.DEBUG: Read existing security token from the session. {"key":"_security_main","token_class":"Symfony\\Component\\Security\\Guard\\Token\\PostAuthenticationGuardToken"} []
[2021-02-24T19:12:59.614651+01:00] doctrine.DEBUG: SELECT t0.id AS id_1, t0.email AS email_2, t0.roles AS roles_3, t0.password AS password_4, t0.is_verified AS is_verified_5 FROM user t0 WHERE t0.id = ? [1] []
[2021-02-24T19:12:59.616611+01:00] security.DEBUG: User was reloaded from a user provider. {"provider":"Symfony\\Bridge\\Doctrine\\Security\\User\\EntityUserProvider","username":"snadaud@free.fr"} []
[2021-02-24T19:12:59.835334+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"626d67"},"request_uri":"https://logtime.lineac2.fr/_wdt/626d67","method":"GET"} []
[2021-02-24T19:12:59.952625+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://logtime.lineac2.fr/user")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://logtime.lineac2.fr/user\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
[2021-02-24T19:54:25.003899+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /\" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\NoConfigurationException(code: 0):  at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:182)"} []
[2021-02-24T19:54:25.221230+01:00] request.INFO: Matched route "_wdt". {"route":"_wdt","route_parameters":{"_route":"_wdt","_controller":"web_profiler.controller.profiler::toolbarAction","token":"350e93"},"request_uri":"https://logtime.lineac2.fr/_wdt/350e93","method":"GET"} []
[2021-02-24T19:54:25.327030+01:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /favicon.ico" (from "https://logtime.lineac2.fr/")" at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php line 136 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException(code: 0): No route found for \"GET /favicon.ico\" (from \"https://logtime.lineac2.fr/\") at /home/hurx6457/public_html/logtime/vendor/symfony/http-kernel/EventListener/RouterListener.php:136)\n[previous exception] [object] (Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException(code: 0): No routes found for \"/favicon.ico/\". at /home/hurx6457/public_html/logtime/vendor/symfony/routing/Matcher/Dumper/CompiledUrlMatcherTrait.php:70)"} []
